#ifndef PRINT_CONTROLS_HPP
# define PRINT_CONTROLS_HPP

// MAIN DATA
# define PRINT_REQUEST 			1
# define PRINT_RESPONSE 		1
# define PRINT_SERVER_CONFIG	0

// METHODS
# define DELETE_PRINT			1
# define POST_PRINT				1
# define GET_PRINT				1

// PARSER
# define BODYPARSER_PRINT		0
# define MULTIPART_PRINT		1

#endif