server {
    listen = 0.0.0.0:8080;
    listen = 127.0.0.1:8081;
    listen = 127.0.0.1:8082;
    server_name = meinewebsite.com;

    error_page 404 = /errors/404.html;
    error_page 500 = /errors/500.html;

    client_max_body_size = 2K;

    location / {
        root = /www;
        accepted_methods = GET, POST;
        index = index.html;
        autoindex = on;
    }

    location /www {
        root = /www;
        accepted_methods = GET, POST;
        autoindex = on;
    }
    
    location /cba {
        root = /www;
        index = text.html;
        accepted_methods = GET;
        autoindex = off;
    }

    location /redir {
        return = 301 https://google.com;
    }

    location /upload {
        accepted_methods = POST, DELETE;
        upload_enable = on;
        upload_store = /www/uploads;
        upload_extensions = .txt, .pdf;
    }

    location /submit {
        root = /www/submit;
        accepted_methods = POST;
        form_output_file = form_file.txt;
    }

    location /abc {
        accepted_methods = GET;
        autoindex = on;
    }

    location /cgi-bin {
        accepted_methods = GET, POST;
        root = /cgi-bin;
        cgi_extension = .php, .py;
    }
}