server {
#   listen = 127.0.0.1:8083
    listen = 127.0.0.1:8080;
    listen = 127.0.0.1:8081;
    listen = 127.0.0.1:8082;
    listen = [::1]:8084;
    server_name = meinewebsite.com;

    error_page 404 = /errors/404.html;
    error_page 500 = /errors/500.html;

    client_max_body_size = 2K;
    root = /www;
    
    location / {
        accepted_methods = GET, POST;
        index = index.html;
        autoindex = on;
    }

    location /www {
#        alias = /www;
        accepted_methods = GET, POST, HEAD;
        autoindex = on;
    }
    
    location /redir {
        return = 301 https://google.com;
    }

    location /upload {
        accepted_methods = POST, DELETE;
        upload_enable = on;
        upload_store = /uploads;
        upload_extensions = .txt, .pdf;
    }

    location /submit {
        alias = /submit;
        accepted_methods = POST;
        form_output_file = form_file.txt;
    }

    location /cba {
        alias = /abc;
        accepted_methods = GET;
        autoindex = on;
    }

    location /cgi-bin {
        accepted_methods = GET, POST;
        alias = /cgi-bin;
        cgi_extension = .php, .py;
    }
}
