# Globaler Bereich
max_body_size = 10M; # Zentrales Limit (kann im Server überschrieben werden)

# WEBSITE 1: Die Hauptseite mit CGI und Uploads
server {
    listen = 0.0.0.0:8080;          # Interface:Port Paar 1
    listen = 127.0.0.1:8081;         # Interface:Port Paar 2 (Zweite Website)
    server_name = meinewebsite.com;

    # Default Error Pages
    error_page 404 = /errors/404.html;
    error_page 500 = /errors/500.html;

    client_max_body_size = 2M;       # Maximal erlaubte Request-Größe für diesen Server

    # Route 1: Standard-Verzeichnis
    location / {
        root = /tmp/www;
        accepted_methods = GET, POST;
        index = index.html;          # Default-Datei für Verzeichnisse
        autoindex = on;              # Directory Listing erlauben
    }

    # Route 2: Das von euch genannte Beispiel /kapouet
    location /kapouet {
        root = /tmp/www/kapouet_folder;
        accepted_methods = GET;
        autoindex = off;             # Directory Listing verboten
    }

    # Route 3: Weiterleitung (HTTP Redirection)
    location /altes-ziel {
        return = 301 https://google.com;
    }

    # Route 4: Datei-Uploads erlauben
    location /upload {
        accepted_methods = POST, DELETE;
        upload_enable = on;
        upload_store = /tmp/www/uploads; # Speicherort für Client-Dateien
    }

    # Route 5: CGI-Ausführung aktivieren
    location /cgi-bin {
        accepted_methods = GET, POST;
        root = /tmp/www/cgi-bin;
        cgi_extension = .php, .py;   # CGI basierend auf Endung ausführen
    }
}

# 1.
# Define all the interface:port pairs on which your server will
#	listen to (defining multiple websites served by your program).
#	===> listen = 0.0.0.0:8080;

# 2.
# set up default error pages.
#	===> error_page 404 = /errors/404.html;

# 3.
# set the maximum allowd size of request-body.
# 	===> client_max_bdoy_size = 2M;

# 4.
# Specify rules or configurations on a URL/route (no regex required here), for a
# website, among the following: