#ifndef PRINT_CONTROLS_HPP
# define PRINT_CONTROLS_HPP

// MAIN DATA
# define PRINT_RAW_REQUEST		1
# define PRINT_PARSED_REQUEST	1
# define PRINT_RESPONSE 		1
# define PRINT_SERVER_CONFIG	1
# define PRINT_LOCATION			1
# define PRINT_MODIFIED_URI		1

// DEBUG
# define DEBUG_PRINT			0

#endif
